/* eslint-disable import/no-anonymous-default-export */
export default {
  about: "O CZEDDu",
  search: "Vyhledat slovo",
  contact: "Kontakt",
  title: "Český elektronický derivační slovník",
  example: "např. učitel",
  name: "Jméno",
  subject: "Předmět",
  subject_example: "Lingvistický problém",
  message: "Zpráva",
  message_example: "Dobrý den, díval jsem se na verbální prefixy...",
  send: "Odeslat",
  thanks: "Děkuji, ozveme se Vám.",
  example_words: "příbuzná slova",
  found_word: "hledané slovo",
  desc_definition: "definice",
  formation: "utvořenost",
  language_level: "jazyková úroveň",
  characteristic: "bližší popis",
  example_sentences: "příkladové věty",
};
